[package]
name = "streaming_calc_actixweb"
version = "0.1.0"
authors = ["sycured <60801403+sycured@users.noreply.github.com>"]
edition = "2018"
repository = "https://github.com/sycured/streaming_calc_actixweb"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
env_logger = "0"
serde = "1"
serde_json = "1"

[dev-dependencies]
actix-rt = "2"

[profile.release]
lto = true

[profile.dev]
opt-level = 3
lto = true