name: Coverage
on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: Swatinem/rust-cache@v1
        with:
          sharedKey: scaw
          cache-on-failure: true

      - name: Install tarpaulin
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-tarpaulin

      - name: Run cargo-tarpaulin
        uses: actions-rs/cargo@v1
        with:
          command: tarpaulin
          args: --verbose --all-features --frozen --workspace --timeout 480 --out Xml

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
